import re
import random
from huggingface_hub import login
import os
import torch
from transformers import AutoTokenizer, pipeline, AutoModelForCausalLM, BitsAndBytesConfig
from CumulativeSummarizer import CumulativeMafiaSummarizer
from Prompts import mafia_prompt, villager_prompt, detective_prompt, doctor_prompt

class LLMAgent():
    def __init__(self, model_name: str, hf_token : str = None, device: str = "auto", max_new_tokens: int = 2500,
                 hf_kwargs: dict = None,):
        """
        Initialize the Hugging Face local agent.
        
        Args:
            model_name (str): The name of the model.
            device (str): Device to use for model inference (default: "auto").
            quantize (bool): Whether to load the model in 8-bit quantized format (default: False).
        """
        super().__init__()
        if hf_token:
            os.environ["HUGGINGFACE_TOKEN"] = hf_token
        else:
            hf_token = os.getenv("HUGGINGFACE_TOKEN")
            
        try:
            login(token=hf_token)
            print("Logged into Hugging Face Hub successfully.")
        except Exception as e:
            print(f"Warning: Hugging Face login failed — {e}")

        ## Initialize the Hugging Face model and tokenizer
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        if hf_kwargs is None:
            hf_kwargs = {}
        self.model = AutoModelForCausalLM.from_pretrained(model_name, device_map=device, trust_remote_code=True, **hf_kwargs) 
        self.pipeline = pipeline('text-generation', max_new_tokens=max_new_tokens, model=self.model, tokenizer=self.tokenizer, return_full_text=False)
        self.initilaize_summarizer()

    def initilaize_summarizer(self):
        self.previous_observation = ""
        self.summarizer = CumulativeMafiaSummarizer(self.pipeline)

    def check_and_parse_response(self,response : str) -> str:
        pattern = r'\[(\d+)\]'
        matches = re.findall(pattern, response)
        if not matches:
            options = list(set(self.summarizer.alive_players) - set([self.summarizer.game_setup['my_player_id']]) - set(self.summarizer.game_setup['teammates']))
            sel = random.choice(options)
            return '['+re.search(r"Player (\d+)", sel).group(1)+']'
        return '['+matches[0]+']'

    def __call__(self, observation: str) -> str:
        """
        Process the observation using the Hugging Face model and return the action.
        
        Args:
            observation (str): The input string to process.
        
        Returns:
            str: The response generated by the model.
        """
        try: # Generate a response
            role_match = re.search(r"Your role:\s*([^\n]+)", observation)
            role = role_match.group(1) if role_match else None
            if role == "Villager":
                system_prompt = villager_prompt
            elif role == "Doctor":
                system_prompt = doctor_prompt
            elif role == "Detective":
                system_prompt = detective_prompt
            elif role == "Mafia":
                system_prompt = mafia_prompt
            if self.previous_observation:
                current_round_observation = observation[len(self.previous_observation):].strip()
            else:
                current_round_observation = observation
                setup_summary = self.summarizer.extract_initial_setup(current_round_observation)
    
            summary = self.summarizer.add_round_summary(current_round_observation)
            full_summary = self.summarizer.get_full_summary()

            action = self.summarizer.get_action_prompt(current_round_observation,role)
           
            # Update previous observation for next round
            self.previous_observation = observation
            messages = [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": full_summary + '\n' + action},
            ]
            prompt = self.pipeline.tokenizer.apply_chat_template(messages, tokenize=False,add_generation_prompt=True)
            response = self.pipeline(prompt)[0]['generated_text']

            if "YOUR RESPONSE MUST BE ONE AND ONLY ONE OF THESE EXACT STRINGS" in action or action=='':
                response = self.check_and_parse_response(response)

            return response
        except Exception as e:
            return f"An error occurred: {e}"